/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DriverSignupRouteImport } from './routes/driver-signup'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityGuidelinesRouteImport } from './routes/community-guidelines'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as DriverDashboardRouteImport } from './routes/driver.dashboard'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportRouteImport } from './routes/app.report'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppNewDeliveryRouteImport } from './routes/app.new-delivery'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as DriverOrdersIdRouteImport } from './routes/driver.orders.$id'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders.$id'
import { Route as ApiPublicDemoDriverEnsureRouteImport } from './routes/api/public/demo-driver-ensure'
import { Route as ApiPublicCheckrWebhookRouteImport } from './routes/api/public/checkr-webhook'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksDispatchTickRouteImport } from './routes/api/public/hooks/dispatch-tick'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSignupRoute = DriverSignupRouteImport.update({
  id: '/driver-signup',
  path: '/driver-signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGuidelinesRoute = CommunityGuidelinesRouteImport.update({
  id: '/community-guidelines',
  path: '/community-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDashboardRoute = DriverDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DriverRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppNewDeliveryRoute = AppNewDeliveryRouteImport.update({
  id: '/new-delivery',
  path: '/new-delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const DriverOrdersIdRoute = DriverOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => DriverRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdersRoute,
} as any)
const ApiPublicDemoDriverEnsureRoute =
  ApiPublicDemoDriverEnsureRouteImport.update({
    id: '/api/public/demo-driver-ensure',
    path: '/api/public/demo-driver-ensure',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCheckrWebhookRoute = ApiPublicCheckrWebhookRouteImport.update({
  id: '/api/public/checkr-webhook',
  path: '/api/public/checkr-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchTickRoute =
  ApiPublicHooksDispatchTickRouteImport.update({
    id: '/api/public/hooks/dispatch-tick',
    path: '/api/public/hooks/dispatch-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/driver': typeof DriverRouteWithChildren
  '/driver-signup': typeof DriverSignupRoute
  '/drivers': typeof DriversRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/new-delivery': typeof AppNewDeliveryRoute
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/report': typeof AppReportRoute
  '/app/settings': typeof AppSettingsRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/api/public/checkr-webhook': typeof ApiPublicCheckrWebhookRoute
  '/api/public/demo-driver-ensure': typeof ApiPublicDemoDriverEnsureRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/driver/orders/$id': typeof DriverOrdersIdRoute
  '/api/public/hooks/dispatch-tick': typeof ApiPublicHooksDispatchTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/driver': typeof DriverRouteWithChildren
  '/driver-signup': typeof DriverSignupRoute
  '/drivers': typeof DriversRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/new-delivery': typeof AppNewDeliveryRoute
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/report': typeof AppReportRoute
  '/app/settings': typeof AppSettingsRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/api/public/checkr-webhook': typeof ApiPublicCheckrWebhookRoute
  '/api/public/demo-driver-ensure': typeof ApiPublicDemoDriverEnsureRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/driver/orders/$id': typeof DriverOrdersIdRoute
  '/api/public/hooks/dispatch-tick': typeof ApiPublicHooksDispatchTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/community-guidelines': typeof CommunityGuidelinesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/driver': typeof DriverRouteWithChildren
  '/driver-signup': typeof DriverSignupRoute
  '/drivers': typeof DriversRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/safety': typeof SafetyRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/new-delivery': typeof AppNewDeliveryRoute
  '/app/orders': typeof AppOrdersRouteWithChildren
  '/app/report': typeof AppReportRoute
  '/app/settings': typeof AppSettingsRoute
  '/driver/dashboard': typeof DriverDashboardRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/api/public/checkr-webhook': typeof ApiPublicCheckrWebhookRoute
  '/api/public/demo-driver-ensure': typeof ApiPublicDemoDriverEnsureRoute
  '/app/orders/$id': typeof AppOrdersIdRoute
  '/driver/orders/$id': typeof DriverOrdersIdRoute
  '/api/public/hooks/dispatch-tick': typeof ApiPublicHooksDispatchTickRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/app'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/driver'
    | '/driver-signup'
    | '/drivers'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/safety'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/applications'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/orders'
    | '/admin/reports'
    | '/app/dashboard'
    | '/app/new-delivery'
    | '/app/orders'
    | '/app/report'
    | '/app/settings'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/api/public/checkr-webhook'
    | '/api/public/demo-driver-ensure'
    | '/app/orders/$id'
    | '/driver/orders/$id'
    | '/api/public/hooks/dispatch-tick'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/app'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/driver'
    | '/driver-signup'
    | '/drivers'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/safety'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/applications'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/orders'
    | '/admin/reports'
    | '/app/dashboard'
    | '/app/new-delivery'
    | '/app/orders'
    | '/app/report'
    | '/app/settings'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/api/public/checkr-webhook'
    | '/api/public/demo-driver-ensure'
    | '/app/orders/$id'
    | '/driver/orders/$id'
    | '/api/public/hooks/dispatch-tick'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/admin'
    | '/app'
    | '/community-guidelines'
    | '/contact'
    | '/cookies'
    | '/driver'
    | '/driver-signup'
    | '/drivers'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/safety'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin/applications'
    | '/admin/dashboard'
    | '/admin/drivers'
    | '/admin/orders'
    | '/admin/reports'
    | '/app/dashboard'
    | '/app/new-delivery'
    | '/app/orders'
    | '/app/report'
    | '/app/settings'
    | '/driver/dashboard'
    | '/driver/earnings'
    | '/api/public/checkr-webhook'
    | '/api/public/demo-driver-ensure'
    | '/app/orders/$id'
    | '/driver/orders/$id'
    | '/api/public/hooks/dispatch-tick'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CommunityGuidelinesRoute: typeof CommunityGuidelinesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DriverRoute: typeof DriverRouteWithChildren
  DriverSignupRoute: typeof DriverSignupRoute
  DriversRoute: typeof DriversRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  SafetyRoute: typeof SafetyRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiPublicCheckrWebhookRoute: typeof ApiPublicCheckrWebhookRoute
  ApiPublicDemoDriverEnsureRoute: typeof ApiPublicDemoDriverEnsureRoute
  ApiPublicHooksDispatchTickRoute: typeof ApiPublicHooksDispatchTickRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-signup': {
      id: '/driver-signup'
      path: '/driver-signup'
      fullPath: '/driver-signup'
      preLoaderRoute: typeof DriverSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-guidelines': {
      id: '/community-guidelines'
      path: '/community-guidelines'
      fullPath: '/community-guidelines'
      preLoaderRoute: typeof CommunityGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/dashboard': {
      id: '/driver/dashboard'
      path: '/dashboard'
      fullPath: '/driver/dashboard'
      preLoaderRoute: typeof DriverDashboardRouteImport
      parentRoute: typeof DriverRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/report': {
      id: '/app/report'
      path: '/report'
      fullPath: '/app/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new-delivery': {
      id: '/app/new-delivery'
      path: '/new-delivery'
      fullPath: '/app/new-delivery'
      preLoaderRoute: typeof AppNewDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/driver/orders/$id': {
      id: '/driver/orders/$id'
      path: '/orders/$id'
      fullPath: '/driver/orders/$id'
      preLoaderRoute: typeof DriverOrdersIdRouteImport
      parentRoute: typeof DriverRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/api/public/demo-driver-ensure': {
      id: '/api/public/demo-driver-ensure'
      path: '/api/public/demo-driver-ensure'
      fullPath: '/api/public/demo-driver-ensure'
      preLoaderRoute: typeof ApiPublicDemoDriverEnsureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkr-webhook': {
      id: '/api/public/checkr-webhook'
      path: '/api/public/checkr-webhook'
      fullPath: '/api/public/checkr-webhook'
      preLoaderRoute: typeof ApiPublicCheckrWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-tick': {
      id: '/api/public/hooks/dispatch-tick'
      path: '/api/public/hooks/dispatch-tick'
      fullPath: '/api/public/hooks/dispatch-tick'
      preLoaderRoute: typeof ApiPublicHooksDispatchTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReportsRoute: typeof AdminReportsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReportsRoute: AdminReportsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppOrdersRouteChildren {
  AppOrdersIdRoute: typeof AppOrdersIdRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersIdRoute: AppOrdersIdRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppNewDeliveryRoute: typeof AppNewDeliveryRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppReportRoute: typeof AppReportRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppNewDeliveryRoute: AppNewDeliveryRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppReportRoute: AppReportRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DriverRouteChildren {
  DriverDashboardRoute: typeof DriverDashboardRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverOrdersIdRoute: typeof DriverOrdersIdRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverDashboardRoute: DriverDashboardRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverOrdersIdRoute: DriverOrdersIdRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CommunityGuidelinesRoute: CommunityGuidelinesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DriverRoute: DriverRouteWithChildren,
  DriverSignupRoute: DriverSignupRoute,
  DriversRoute: DriversRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  SafetyRoute: SafetyRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiPublicCheckrWebhookRoute: ApiPublicCheckrWebhookRoute,
  ApiPublicDemoDriverEnsureRoute: ApiPublicDemoDriverEnsureRoute,
  ApiPublicHooksDispatchTickRoute: ApiPublicHooksDispatchTickRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
